name: cicd

on:
  push:
    paths:
      - 'src/**'
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Shorten Commit ID
        shell: bash
        run: |
          set -euo pipefail
          # 7 karakterlik kısa SHA üret
          SHORT_SHA="$(echo "${GITHUB_SHA}" | cut -c1-7)"
          # Boşsa hata ver (tag boş kalmasın)
          if [ -z "$SHORT_SHA" ]; then
            echo "SHORT_SHA boş! GITHUB_SHA: ${GITHUB_SHA}"
            exit 1
          fi
          echo "COMMIT_ID=$SHORT_SHA" >> "$GITHUB_ENV"
          echo "Kullanılacak tag: $SHORT_SHA"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: gokhangurbuz/python-app:${{ env.COMMIT_ID }}
  
  cd:
    needs: ci
    runs-on: self-hosted
    steps:
      - name: Install ArgoCD CLI
        shell: bash
        run: |
          curl -ksSL -o argocd https://argocd-server.argocd/downloads/argocd-linux-amd64
          chmod +x argocd
          sudo mv ./argocd /usr/local/bin/argocd

      - name: ArgoCd app sync
        shell: bash
        run: |
          argocd login argocd-server.argocd \
          --insecure \
          --grpc-web \
          -u admin \
          -p ${{ secrets.ARGOCD_PASSWORD }} && \
          argocd app sync my-app
